services:
  summrpro:
    image: devehab/summrpro:latest  # Replace with your Docker Hub image
    container_name: summrpro
    restart: unless-stopped
    ports:
      - "5003:5003"  # Expose the application on port 5003
    environment:
      - FLASK_ENV=production  # Example: Set environment variables if needed
      - FLASK_APP=app.py
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
